version: "2.1"
services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    environment:
      - TZ=Europe/Athens
      - PUID=${PUID}  # Set user ID dynamically
      - PGID=${PGID}  # Set group ID dynamically
    user: "${PUID}:${PGID}"  # Use variables for UID/GID
    volumes:
      - /var/cache/ntfy:/var/cache/ntfy
      - /etc/ntfy:/etc/ntfy
    ports:
      - 80:80
    restart: unless-stopped

